## EDA for feature 2-23

In [3]:
# loading libraries
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

# show all columns of df
pd.set_option('display.max_columns', None)

# disable warning
import warnings
warnings.filterwarnings('ignore')

In [24]:
# Constants
file = "../data/dataset_phishing.csv"

sample_url = "https://www.youtube.com/watch?v=BEki_rsWu4E"

In [15]:
# Load the file
dat = pd.read_csv(file)
mine = dat.iloc[:,np.r_[1:23, 88]]
mine

,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,nb_underscore,nb_tilde,nb_percent,nb_slash,nb_star,nb_colon,nb_comma,nb_semicolumn,nb_dollar,nb_space,nb_www,nb_com,status
0,37,19,0,3,0,0,0,0,0,0,0,0,0,3,0,1,0,0,0,0,1,0,legitimate
1,77,23,1,1,0,0,0,0,0,0,0,0,0,5,0,1,0,0,0,0,0,0,phishing
2,126,50,1,4,1,0,1,2,0,3,2,0,0,5,0,1,0,0,0,0,0,1,phishing
3,18,11,0,2,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,legitimate
4,55,15,0,2,2,0,0,0,0,0,0,0,0,5,0,1,0,0,0,0,1,0,legitimate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11425,45,17,0,2,0,0,0,0,0,0,0,0,0,4,0,1,0,0,0,0,1,0,legitimate
11426,84,18,0,5,0,1,1,0,0,1,0,0,1,5,0,1,0,0,0,1,1,1,phishing
11427,105,16,1,2,6,0,1,0,0,1,1,0,0,5,0,1,0,0,0,0,1,0,legitimate
11428,38,30,0,2,0,0,0,0,0,0,0,0,0,3,0,1,0,0,0,0,1,0,legitimate
11429,477,14,1,24,0,1,1,9,0,9,18,0,23,4,0,1,0,9,0,0,1,0,phishing

In [16]:
# Checking for any missing values at any column
mine.isna().sum()

length_url         0
length_hostname    0
ip                 0
nb_dots            0
nb_hyphens         0
nb_at              0
nb_qm              0
nb_and             0
nb_or              0
nb_eq              0
nb_underscore      0
nb_tilde           0
nb_percent         0
nb_slash           0
nb_star            0
nb_colon           0
nb_comma           0
nb_semicolumn      0
nb_dollar          0
nb_space           0
nb_www             0
nb_com             0
status             0
dtype: int64

In [19]:
# Check data type
mine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11430 entries, 0 to 11429
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   length_url       11430 non-null  int64
 1   length_hostname  11430 non-null  int64
 2   ip               11430 non-null  int64
 3   nb_dots          11430 non-null  int64
 4   nb_hyphens       11430 non-null  int64
 5   nb_at            11430 non-null  int64
 6   nb_qm            11430 non-null  int64
 7   nb_and           11430 non-null  int64
 8   nb_or            11430 non-null  int64
 9   nb_eq            11430 non-null  int64
 10  nb_underscore    11430 non-null  int64
 11  nb_tilde         11430 non-null  int64
 12  nb_percent       11430 non-null  int64
 13  nb_slash         11430 non-null  int64
 14  nb_star          11430 non-null  int64
 15  nb_colon         11430 non-null  int64
 16  nb_comma         11430 non-null  int64
 17  nb_semicolumn    11430 non-null  int64
 18  nb_dollar        11430 non-null  int64
 19  nb_space         11430 non-null  int64
 20  nb_www           11430 non-null  int64
 21  nb_com           11430 non-null  int64
 22  status           11430 non-null  object
dtypes: int64(22), object(1)
memory usage: 2.0+ MB

In [20]:
# Check summary stats
mine.describe()

,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,nb_underscore,nb_tilde,nb_percent,nb_slash,nb_star,nb_colon,nb_comma,nb_semicolumn,nb_dollar,nb_space,nb_www,nb_com
count,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.0,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000
mean,61.126684,21.090289,0.150569,2.480752,0.997550,0.022222,0.141207,0.162292,0.0,0.293176,0.322660,0.006649,0.123097,4.289589,0.000700,1.027909,0.004024,0.062292,0.001925,0.034821,0.448469,0.127997
std,55.297318,10.777171,0.357644,1.369686,2.087087,0.155500,0.364456,0.821337,0.0,0.998317,1.093336,0.081274,1.466450,1.882251,0.026448,0.240325,0.103240,0.598190,0.077111,0.375576,0.501912,0.379008
min,12.000000,4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,33.000000,15.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,47.000000,19.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,71.000000,24.000000,0.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,1641.000000,214.000000,1.000000,24.000000,43.000000,4.000000,3.000000,19.000000,0.0,19.000000,18.000000,1.000000,96.000000,33.000000,1.000000,7.000000,4.000000,20.000000,6.000000,18.000000,2.000000,6.000000

In [23]:
# What each columns means (according to the data description paper)

0         37
1         77
2        126
3         18
4         55
        ...
11425     45
11426     84
11427    105
11428     38
11429    477
Name: length_url, Length: 11430, dtype: int64